### PR TITLE
fix: coroutine.c

### PR DESCRIPTION
**Pull request by AnHsiL**
## Types of changes
**Thanks for sending a pull request! Please fill in the following content to let us know better about this change.**
Please put an `x` in the box that applies

- [x] **Bugfix**
- [ ] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description
**Describe what the change is**
刪除不知道為什麼多加了的東西

## Expected behavior
work successfully.

## Related Issue
no

## More Information
**Screenshots**

**Additional context**
Add any other context about the problem here. You may also want to refer
to [how to wirte the perfect pull request](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)

### CODE REVIEW

**Review by AnHsiL — COMMENTED** [review]
20221028

**Review by AnChen01057201 — COMMENTED** [review]
ok

**Review by AnChen01057201 — COMMENTED** [review]
ok

**Review by AnHsiL — COMMENTED** [review]
20221028 19:48 OK

**Review by AnHsiL — COMMENTED** [review]
ok

**Review by VicTang00957032 — APPROVED** [review]

**Pull request merged**
